### PR TITLE
generic check for toml_rb gem version

### PR DESCRIPTION
**Pull request by zoojar**
fixes: https://github.com/puppetlabs/influxdb/issues/54

### CODE REVIEW

**Review by MartyEwings — CHANGES_REQUESTED** [review]
Nice catch thanks

Would it be possible to look at the static code test outputs, you have a minor styling thing, the double quotes need switched out for single

**Review by jarretlavallee — CHANGES_REQUESTED** [review]
Thanks for the contribution. `puppetserver gem` has to spin up a JVM instance and is quite slow. This fact is confined to all Linux agents, so we may see failures on agents that don't have the `puppetserver` executable. 

In the `puppetserver_gem` package provider we migrated away from using `puppetserver gem list` to [this method.](https://github.com/puppetlabs/puppet/blob/main/lib/puppet/provider/package/puppetserver_gem.rb#L130-L170) However, that approach may be a bit heavy for this fact. What about a change where we look for `/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/toml-rb-*`

**Review by jarretlavallee — APPROVED** [review]
That was a really quick turnaround. Thanks!

**Comment by zoojar** [comment]
No worries. Cheers!

**Comment by bastelfreak** [comment]
I'm wondering, what even is the purpose of that fact? It seems like it's not used anywhere in the code?

**Comment by zoojar** [comment]
Great question. I wondered this too!
The provider fails if the gem isn't installed
https://github.com/puppetlabs/influxdb/blob/80f406eb221501aa50364c5b9d875624a4f4e91f/lib/puppet/functions/influxdb/from_toml.rb#L1

so I use it from a profile to check the package exists and declare it if it
doesn't.
Perhaps a better solution is a manage_package param?

**Comment by m0dular** [comment]
I looked into this, and it currently is not used.  We previously used a `file` resource to check if the gem were installed, but this caused the catalog compilation to fail and I couldn't think of a better solution, other than letting the compilation fail with the `toml-rb` error.

What do you guys think we should do regarding the gem version and fact?  I'm leaning towards just removing the fact, unless we can think of a good way to use it.

**Comment by zoojar** [comment]
It's a nice bit of functionality for checking the package, and it doesn't
affect or depend on anything so I'm in favour of keeping it.

**Comment by bastelfreak** [comment]
I don't see any purpose for the fact and since every fact costs some performance, I vote for removing it. Of course the required CPU time for a single fact is low, but boxes usually have a lot of facts and it sums up.

**Comment by zoojar** [comment]
Agreed

**Comment by jarretlavallee** [comment]
Closing as #58 removes this fact.

**Pull request closed without merging**
