### PR TITLE
provide an option to disable installing from source

### PR DESCRIPTION
**Pull request by vchepkov**

### CODE REVIEW

**Comment by m0dular** [comment]
Good catch, thank you @vchepkov!  We have a changelog generator that will actually update `REFERENCE.md` when we do a release, so could you remove the change to it in this PR?  Then I think we'll be good to merge this.

I'll also add a test to cover the combinations of `$manage_repo` and `$archive_source`.

**Comment by vchepkov** [comment]
Certainly, I will update description of the parameter instead

**Comment by vchepkov** [comment]
Done

**Comment by m0dular** [comment]
Failures are due to SLES 15 not having `netstat`, which the Serverspec tests use behind the scenes.  I'll make the same change as [here](https://github.com/puppetlabs/puppet_operational_dashboards/commit/cf653b981c5dc46f9804dd8711155f1260dc56e0) in the spec test PR, which I'll make later today.

Thanks again for using and contributing!

**Review by m0dular — APPROVED** [review]

**Comment by vchepkov** [comment]
@m0dular , unfortunately, this brought up another defect - service influxdb is only defined if configured via yumrepo or achive_source. Imho, it should be  out of both blocks

**Pull request merged**
