### PR TITLE
Add options to set custom influxdb repo.

### LINKED ISSUE #28: provide alternative path for the repository
Currently, module provides only two options for installation sources - either predefined yumrepo or archive_source
module should provide ability to define a custom yumrepo baseurl, to accommodate environments where external sources are not allowed

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
fixes #28

### CODE REVIEW

**Review by m0dular — CHANGES_REQUESTED** [review]
Thanks, this is a nice addition :+1: 

But would it be better to only have the changes from 3c41763f that are related to the repository changes in this branch?  We can always rebase the feature branches before merging them, and I think it would play nicer with the changelog generator if each feature only has the related commits.

**Comment by SimonHoenscheid** [comment]
Yes, it was my plan to rebase the commits before these are merged.

**Comment by SimonHoenscheid** [comment]
@m0dular added the changes you suggested and rebased. Should be ready to merge.

**Comment by SimonHoenscheid** [comment]
@MartyEwings @m0dular do you need changes or is the PR ready to merge.

**Comment by MartyEwings** [comment]
@SimonHoenscheid sorry, there is some leave on my team this week, so I'm doing some prioritisation, ill have a look as soon as i can but it looks good

**Comment by m0dular** [comment]
Sorry, I was out the past couple of weeks.  This looks good, acceptance tests are green, and I think the existing unit tests cover these changes, so we'll merge it :+1:

**Comment by m0dular** [comment]
Just a quick note about the git history, I noticed these changes were in a merge commit for the lint changes, #31.  I pulled the PR changes out to their own commit, rebased from `main` to pick up some README additions, and amended the commit so that @SimonHoenscheid is the author.  Normally I wouldn't force push someone else's branch, but since this PR is ready I went ahead and did it so we can merge it here.

**Pull request merged**
