### PR TITLE
Check if token file exists on disk

### PR DESCRIPTION
**Pull request by m0dular**
This commit checks if the admin_token_file exists on disk before reading
it in the retrieve_token() function.

### CODE REVIEW

**Review by jarretlavallee — APPROVED** [review]
Does the code that use this function handle a nil/undef result? You may have to return a default string.

**Comment by m0dular** [comment]
It does, in the sense that it will create a `Sensitive[undef]` value.  That causes the Telegraf override file and the Grafana datasource to use an empty token, which I guess is the expected behavior?

**Comment by jarretlavallee** [comment]
Sounds good.

**Comment by m0dular** [comment]
Centos 7 was hung on "Installing PE" for about 40 minutes, so I killed it.

**Pull request merged**
